# Generated by Django 2.1.15 on 2021-12-10 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartamente_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipapartament',
            old_name='Denumire',
            new_name='denumire',
        ),
        migrations.AddField(
            model_name='aplicantiapartament',
            name='status',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='locuitoriapartament',
            name='locuieste_in_prezent',
            field=models.BooleanField(default=True),
        ),
    ]
