# Generated by Django 2.1.15 on 2021-12-10 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartamente_api', '0002_auto_20211210_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipapartament',
            name='apartamente',
            field=models.ManyToManyField(related_name='apartamente', to='apartamente_api.Apartament'),
        ),
    ]
