# Generated by Django 2.1.15 on 2021-12-10 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartamente_api', '0003_tipapartament_apartamente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipapartament',
            name='apartamente',
            field=models.ManyToManyField(default=None, related_name='apartamente', to='apartamente_api.Apartament'),
        ),
    ]
