# Generated by Django 2.1.15 on 2021-12-10 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartamente_api', '0005_auto_20211210_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipapartament',
            name='apartamente',
        ),
    ]
