# Generated by Django 2.1.15 on 2021-12-11 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartamente_api', '0006_remove_tipapartament_apartamente'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartament',
            name='metri_patrati',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
    ]
